CREATE TABLE `ST_DISPOSITIVO` (
	`ID_DISPOSITIVO` text PRIMARY KEY NOT NULL,
	`S_UUID` text NOT NULL,
	`S_NOME` text,
	`S_DESCRICAO` text,
	`S_CODIGO` text NOT NULL,
	`S_STATUS` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `ST_DISPOSITIVO_S_UUID_unique` ON `ST_DISPOSITIVO` (`S_UUID`);--> statement-breakpoint
CREATE UNIQUE INDEX `ST_DISPOSITIVO_S_CODIGO_unique` ON `ST_DISPOSITIVO` (`S_CODIGO`);